#!/usr/bin/env python3
"""embed_c6_catalog - bake a catalog of ESP32-C6 firmware builds into an OG app.

Reads a manifest.json (images[] + builds[]) and emits three sources:

  c6_catalog_images.S   .incbin of each unique image, into MAIN flash
  c6_catalog_main.c     fwog_c6_catalog[]      (image ptrs+sizes) -- MAIN links
  c6_catalog_meta.c     fwog_c6_catalog_meta[] (name/description/when) -- DISPLAY

The image bytes live only in MAIN; the DISPLAY side gets metadata only, so the
DECK chooser can show names + descriptions without carrying ~700 KB per build.
Both are generated from the one manifest -- a single source of truth.

.incbin (not C arrays) for the same reason genimage.py uses it: a 640 KB app
as hex is a multi-MB source the cross-compiler re-parses every build.

manifest.json shape:
  { "images": [ {"id": "venom_app", "file": "venom/venom.bin"}, ... ],
    "builds": [ {"slug","name","version","description","when",
                 "boot": <img id>, "part": <img id>, "app": <img id>}, ... ] }

The three ESP32-C6 flash offsets are fixed: bootloader 0x0, partition 0x8000,
app 0x10000 -- callers do not choose them.
"""
import argparse
import json
import os
import pathlib

OFFSETS = (0x0, 0x8000, 0x10000)   # boot, partition, app
SLOTS = ("boot", "part", "app")


def c_str(s):
    s = (s or "").replace("\\", "\\\\").replace('"', '\\"')
    s = "".join(c for c in s if 0x20 <= ord(c) < 0x7F)
    return s


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--manifest", required=True)
    ap.add_argument("--out-asm", required=True)
    ap.add_argument("--out-main", required=True)
    ap.add_argument("--out-meta", required=True)
    args = ap.parse_args()

    manifest_path = pathlib.Path(args.manifest).resolve()
    base = manifest_path.parent
    m = json.loads(manifest_path.read_text())
    images = {img["id"]: img for img in m.get("images", [])}
    builds = m.get("builds", [])
    if not builds:
        raise SystemExit("embed_c6_catalog: manifest has no builds[]")

    # Which images are actually referenced (incbin only those).
    used = []
    for b in builds:
        for slot in SLOTS:
            iid = b[slot]
            if iid not in images:
                raise SystemExit(f"build '{b.get('slug')}' references unknown image '{iid}'")
            if iid not in used:
                used.append(iid)

    def sym(iid):
        return "c6img_" + "".join(ch if ch.isalnum() else "_" for ch in iid)

    # --- images .S + exact byte sizes (from the files themselves; a symbol
    # difference `end - start` is NOT a constant expression a static
    # initializer can use, so we emit literal sizes here) ---
    sizes = {}
    asm = ["/* Generated by tools/embed_c6_catalog.py -- do not edit. */",
           '    .section .rodata.c6_catalog, "a"']
    for iid in used:
        f = (base / images[iid]["file"]).resolve()
        if not f.exists():
            raise SystemExit(f"image '{iid}' file not found: {f}")
        sizes[iid] = f.stat().st_size
        s = sym(iid)
        asm += [f"    .balign 4",
                f"    .global {s}", f"{s}:", f'    .incbin "{f.as_posix()}"']
    pathlib.Path(args.out_asm).write_text("\n".join(asm) + "\n")

    # --- MAIN catalog .c ---
    externs = [f"extern const uint8_t {sym(iid)}[];" for iid in used]
    rows = []
    for b in builds:
        pieces = []
        for slot, off in zip(SLOTS, OFFSETS):
            iid = b[slot]
            pieces.append(f"{{ {sym(iid)}, {sizes[iid]}u, 0x{off:x}u }}")
        rows.append("    { { " + ", ".join(pieces) + " } },")
    main_c = [
        "/* Generated by tools/embed_c6_catalog.py -- do not edit. */",
        '#include "c6flash/fwog_c6flash.h"', "",
        *externs, "",
        "const fwog_c6_build_t fwog_c6_catalog[] = {",
        *rows,
        "};",
        "const unsigned fwog_c6_catalog_count = "
        "sizeof fwog_c6_catalog / sizeof fwog_c6_catalog[0];",
    ]
    pathlib.Path(args.out_main).write_text("\n".join(main_c) + "\n")

    # --- DISPLAY metadata .c ---
    meta_rows = []
    for b in builds:
        meta_rows.append('    {{ "{}", "{}", "{}" }},'.format(
            c_str(b.get("name", b.get("slug", "?"))),
            c_str(b.get("description", "")),
            c_str(b.get("when", ""))))
    meta_c = [
        "/* Generated by tools/embed_c6_catalog.py -- do not edit. */",
        '#include "ui/fwog_c6flash_ui.h"', "",
        "const fwog_c6_meta_t fwog_c6_catalog_meta[] = {",
        *meta_rows,
        "};",
        "const unsigned fwog_c6_catalog_meta_count = "
        "sizeof fwog_c6_catalog_meta / sizeof fwog_c6_catalog_meta[0];",
    ]
    pathlib.Path(args.out_meta).write_text("\n".join(meta_c) + "\n")


if __name__ == "__main__":
    main()
